### ISSUE TITLE
咪咕视频 解析疑问

### ISSUE THREAD

**Issue by huang880** [jym66/Dlink_Parse#1]
你好，我想问一个关于咪咕视频解析的疑问，就是解析出最后的url的参数ddCalcu的值是如何知晓它的生成规律的？因为看到你的代码中是直接写好的生成逻辑，如果你是通过不断测试最后总结出来的规律那就太厉害了。是否是哪个js中有这个生成的逻辑代码呢？望解答！谢谢了。

**Comment by jym66** [comment]
你好，可以用Chrome浏览器全局搜索ddCalcu可以找到一个叫pcPlayer.js的文件,在7000行左右可以看到生成方法.
