### ISSUE TITLE
西瓜解析好像又更新了

### ISSUE THREAD

**Issue by dplcz** [jym66/Dlink_Parse#10]
在base64.b64decode时发生Invalid base64-encoded string: number of data characters (769) cannot be 1 more than a multiple of 4错误

**Comment by 9ihbd2DZSMjtsf7vecXjz** [comment]
同步关注 ,请教使用方法,如何调用?

**Comment by jym66** [comment]
有时间看一下

**Comment by jym66** [comment]
> 在base64.b64decode时发生Invalid base64-encoded string: number of data characters (769) cannot be 1 more than a multiple of 4错误

已更新49175c0

**Comment by jym66** [comment]
已更新 49175c05ef801dcb0b020705d39a0591ed5fbd58

**Comment by jym66** [comment]
> 同步关注 ,请教使用方法,如何调用?

把视频地址，传入 xigua("视频地址").start()就可以了，具体的清晰度等需要自己提取，我这里只简单提取了一下

**Comment by TommyLe1** [comment]
> 已更新 [49175c0](https://github.com/jym66/Dlink_Parse/commit/49175c05ef801dcb0b020705d39a0591ed5fbd58)

你好，我把项目clone下去运行后提示我64和69有语法错误，我修正后在运行还会报错
![image](https://github.com/user-attachments/assets/9cc559dc-11f5-49c0-8e43-94927b44e814)

**Comment by TonyD0g** [comment]
> > 同步关注 ,请教使用方法,如何调用?
> 
> 把视频地址，传入 xigua("视频地址").start()就可以了，具体的清晰度等需要自己提取，我这里只简单提取了一下

貌似不行？
  File "C:\Users\Jarvis\Desktop\download\xigua.py", line 28, in __init__
    '__ac_signature': self.getSign(),
                      ^^^^^^^^^^^^^^
  File "C:\Users\Jarvis\Desktop\download\xigua.py", line 42, in getSign
    ctx = jscode.call("getSign", self.nonce, self.url)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Environment\Python\312\Lib\site-packages\execjs\_abstract_runtime_context.py", line 37, in call
    return self._call(name, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Environment\Python\312\Lib\site-packages\execjs\_external_runtime.py", line 92, in _call
    return self._eval("{identifier}.apply(this, {args})".format(identifier=identifier, args=args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Environment\Python\312\Lib\site-packages\execjs\_external_runtime.py", line 78, in _eval
    return self.exec_(code)
           ^^^^^^^^^^^^^^^^
  File "D:\Environment\Python\312\Lib\site-packages\execjs\_abstract_runtime_context.py", line 18, in exec_
    return self._exec_(source)
           ^^^^^^^^^^^^^^^^^^^
  File "D:\Environment\Python\312\Lib\site-packages\execjs\_external_runtime.py", line 88, in _exec_
    return self._extract_result(output)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Environment\Python\312\Lib\site-packages\execjs\_external_runtime.py", line 167, in _extract_result
    raise ProgramError(value)
execjs._exceptions.ProgramError: SyntaxError: 缺少标识符、字符串或数字

**Comment by jym66** [comment]
> > > 同步关注 ,请教使用方法,如何调用?
> > 
> > 
> > 把视频地址，传入 xigua("视频地址").start()就可以了，具体的清晰度等需要自己提取，我这里只简单提取了一下
> 
> 貌似不行？ File "C:\Users\Jarvis\Desktop\download\xigua.py", line 28, in **init** '__ac_signature': self.getSign(), ^^^^^^^^^^^^^^ File "C:\Users\Jarvis\Desktop\download\xigua.py", line 42, in getSign ctx = jscode.call("getSign", self.nonce, self.url) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Environment\Python\312\Lib\site-packages\execjs_abstract_runtime_context.py", line 37, in call return self._call(name, *args) ^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Environment\Python\312\Lib\site-packages\execjs_external_runtime.py", line 92, in _call return self._eval("{identifier}.apply(this, {args})".format(identifier=identifier, args=args)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Environment\Python\312\Lib\site-packages\execjs_external_runtime.py", line 78, in _eval return self.exec_(code) ^^^^^^^^^^^^^^^^ File "D:\Environment\Python\312\Lib\site-packages\execjs_abstract_runtime_context.py", line 18, in exec_ return self._exec_(source) ^^^^^^^^^^^^^^^^^^^ File "D:\Environment\Python\312\Lib\site-packages\execjs_external_runtime.py", line 88, in _exec_ return self._extract_result(output) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Environment\Python\312\Lib\site-packages\execjs_external_runtime.py", line 167, in _extract_result raise ProgramError(value) execjs._exceptions.ProgramError: SyntaxError: 缺少标识符、字符串或数字

我这边是正常的，你看一下你的nodejs是不是没安装

**Comment by TonyD0g** [comment]
> > > > 同步关注 ,请教使用方法,如何调用?
> > > 
> > > 
> > > 把视频地址，传入 xigua("视频地址").start()就可以了，具体的清晰度等需要自己提取，我这里只简单提取了一下
> > 
> > 
> > 貌似不行？ File "C:\Users\Jarvis\Desktop\download\xigua.py", line 28, in **init** '__ac_signature': self.getSign(), ^^^^^^^^^^^^^^ File "C:\Users\Jarvis\Desktop\download\xigua.py", line 42, in getSign ctx = jscode.call("getSign", self.nonce, self.url) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Environment\Python\312\Lib\site-packages\execjs_abstract_runtime_context.py", line 37, in call return self._call(name, *args) ^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Environment\Python\312\Lib\site-packages\execjs_external_runtime.py", line 92, in _call return self._eval("{identifier}.apply(this, {args})".format(identifier=identifier, args=args)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Environment\Python\312\Lib\site-packages\execjs_external_runtime.py", line 78, in _eval return self.exec_(code) ^^^^^^^^^^^^^^^^ File "D:\Environment\Python\312\Lib\site-packages\execjs_abstract_runtime_context.py", line 18, in exec_ return self._exec_(source) ^^^^^^^^^^^^^^^^^^^ File "D:\Environment\Python\312\Lib\site-packages\execjs_external_runtime.py", line 88, in _exec_ return self._extract_result(output) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Environment\Python\312\Lib\site-packages\execjs_external_runtime.py", line 167, in _extract_result raise ProgramError(value) execjs._exceptions.ProgramError: SyntaxError: 缺少标识符、字符串或数字
> 
> 我这边是正常的，你看一下你的nodejs是不是没安装

解析后获得的链接，如何进行下载呢，访问后显示是403，有鉴权？

**Comment by jym66** [comment]
> > > > > 同步关注 ,请教使用方法,如何调用?
> > > > 
> > > > 
> > > > 把视频地址，传入 xigua("视频地址").start()就可以了，具体的清晰度等需要自己提取，我这里只简单提取了一下
> > > 
> > > 
> > > 貌似不行？ File "C:\Users\Jarvis\Desktop\download\xigua.py", line 28, in **init** '__ac_signature': self.getSign(), ^^^^^^^^^^^^^^ File "C:\Users\Jarvis\Desktop\download\xigua.py", line 42, in getSign ctx = jscode.call("getSign", self.nonce, self.url) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Environment\Python\312\Lib\site-packages\execjs_abstract_runtime_context.py", line 37, in call return self._call(name, *args) ^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Environment\Python\312\Lib\site-packages\execjs_external_runtime.py", line 92, in _call return self._eval("{identifier}.apply(this, {args})".format(identifier=identifier, args=args)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Environment\Python\312\Lib\site-packages\execjs_external_runtime.py", line 78, in _eval return self.exec_(code) ^^^^^^^^^^^^^^^^ File "D:\Environment\Python\312\Lib\site-packages\execjs_abstract_runtime_context.py", line 18, in exec_ return self._exec_(source) ^^^^^^^^^^^^^^^^^^^ File "D:\Environment\Python\312\Lib\site-packages\execjs_external_runtime.py", line 88, in _exec_ return self._extract_result(output) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Environment\Python\312\Lib\site-packages\execjs_external_runtime.py", line 167, in _extract_result raise ProgramError(value) execjs._exceptions.ProgramError: SyntaxError: 缺少标识符、字符串或数字
> > 
> > 
> > 我这边是正常的，你看一下你的nodejs是不是没安装
> 
> 解析后获得的链接，如何进行下载呢，访问后显示是403，有鉴权？

请求头带上 Referer:https://www.ixigua.com

**Comment by TonyD0g** [comment]
> > > > > > 同步关注 ,请教使用方法,如何调用?
> > > > > 
> > > > > 
> > > > > 把视频地址，传入 xigua("视频地址").start()就可以了，具体的清晰度等需要自己提取，我这里只简单提取了一下
> > > > 
> > > > 
> > > > 貌似不行？ File "C:\Users\Jarvis\Desktop\download\xigua.py", line 28, in **init** '__ac_signature': self.getSign(), ^^^^^^^^^^^^^^ File "C:\Users\Jarvis\Desktop\download\xigua.py", line 42, in getSign ctx = jscode.call("getSign", self.nonce, self.url) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Environment\Python\312\Lib\site-packages\execjs_abstract_runtime_context.py", line 37, in call return self._call(name, *args) ^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Environment\Python\312\Lib\site-packages\execjs_external_runtime.py", line 92, in _call return self._eval("{identifier}.apply(this, {args})".format(identifier=identifier, args=args)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Environment\Python\312\Lib\site-packages\execjs_external_runtime.py", line 78, in _eval return self.exec_(code) ^^^^^^^^^^^^^^^^ File "D:\Environment\Python\312\Lib\site-packages\execjs_abstract_runtime_context.py", line 18, in exec_ return self._exec_(source) ^^^^^^^^^^^^^^^^^^^ File "D:\Environment\Python\312\Lib\site-packages\execjs_external_runtime.py", line 88, in _exec_ return self._extract_result(output) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Environment\Python\312\Lib\site-packages\execjs_external_runtime.py", line 167, in _extract_result raise ProgramError(value) execjs._exceptions.ProgramError: SyntaxError: 缺少标识符、字符串或数字
> > > 
> > > 
> > > 我这边是正常的，你看一下你的nodejs是不是没安装
> > 
> > 
> > 解析后获得的链接，如何进行下载呢，访问后显示是403，有鉴权？
> 
> 请求头带上 Referer:https://www.ixigua.com

十分感谢

**Comment by jym66** [comment]
> > > > > > > 同步关注 ,请教使用方法,如何调用?
> > > > > > 
> > > > > > 
> > > > > > 把视频地址，传入 xigua("视频地址").start()就可以了，具体的清晰度等需要自己提取，我这里只简单提取了一下
> > > > > 
> > > > > 
> > > > > 貌似不行？ File "C:\Users\Jarvis\Desktop\download\xigua.py", line 28, in **init** '__ac_signature': self.getSign(), ^^^^^^^^^^^^^^ File "C:\Users\Jarvis\Desktop\download\xigua.py", line 42, in getSign ctx = jscode.call("getSign", self.nonce, self.url) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Environment\Python\312\Lib\site-packages\execjs_abstract_runtime_context.py", line 37, in call return self._call(name, *args) ^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Environment\Python\312\Lib\site-packages\execjs_external_runtime.py", line 92, in _call return self._eval("{identifier}.apply(this, {args})".format(identifier=identifier, args=args)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Environment\Python\312\Lib\site-packages\execjs_external_runtime.py", line 78, in _eval return self.exec_(code) ^^^^^^^^^^^^^^^^ File "D:\Environment\Python\312\Lib\site-packages\execjs_abstract_runtime_context.py", line 18, in exec_ return self._exec_(source) ^^^^^^^^^^^^^^^^^^^ File "D:\Environment\Python\312\Lib\site-packages\execjs_external_runtime.py", line 88, in _exec_ return self._extract_result(output) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Environment\Python\312\Lib\site-packages\execjs_external_runtime.py", line 167, in _extract_result raise ProgramError(value) execjs._exceptions.ProgramError: SyntaxError: 缺少标识符、字符串或数字
> > > > 
> > > > 
> > > > 我这边是正常的，你看一下你的nodejs是不是没安装
> > > 
> > > 
> > > 解析后获得的链接，如何进行下载呢，访问后显示是403，有鉴权？
> > 
> > 
> > 请求头带上 Referer:https://www.ixigua.com
> 
> 十分感谢

不客气

**Comment by TonyD0g** [comment]
大哥，虽然说不会403了，但是视频依旧播放不了，这是我的问题吗，望解答，不胜感激> > > > > > 同步关注 ,请教使用方法,如何调用?
> > > > > 
> > > > > 
> > > > > 把视频地址，传入 xigua("视频地址").start()就可以了，具体的清晰度等需要自己提取，我这里只简单提取了一下
> > > > 
> > > > 
> > > > 貌似不行？ File "C:\Users\Jarvis\Desktop\download\xigua.py", line 28, in **init** '__ac_signature': self.getSign(), ^^^^^^^^^^^^^^ File "C:\Users\Jarvis\Desktop\download\xigua.py", line 42, in getSign ctx = jscode.call("getSign", self.nonce, self.url) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Environment\Python\312\Lib\site-packages\execjs_abstract_runtime_context.py", line 37, in call return self._call(name, *args) ^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Environment\Python\312\Lib\site-packages\execjs_external_runtime.py", line 92, in _call return self._eval("{identifier}.apply(this, {args})".format(identifier=identifier, args=args)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Environment\Python\312\Lib\site-packages\execjs_external_runtime.py", line 78, in _eval return self.exec_(code) ^^^^^^^^^^^^^^^^ File "D:\Environment\Python\312\Lib\site-packages\execjs_abstract_runtime_context.py", line 18, in exec_ return self._exec_(source) ^^^^^^^^^^^^^^^^^^^ File "D:\Environment\Python\312\Lib\site-packages\execjs_external_runtime.py", line 88, in _exec_ return self._extract_result(output) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Environment\Python\312\Lib\site-packages\execjs_external_runtime.py", line 167, in _extract_result raise ProgramError(value) execjs._exceptions.ProgramError: SyntaxError: 缺少标识符、字符串或数字
> > > 
> > > 
> > > 我这边是正常的，你看一下你的nodejs是不是没安装
> > 
> > 解析后获得的链接，如何进行下载呢，访问后显示是403，有鉴权？
> 
> 请求头带上 Referer:https://www.ixigua.com

**Comment by jym66** [comment]
> 大哥，虽然说不会403了，但是视频依旧播放不了，这是我的问题吗，望解答，不胜感激> > > > > > 同步关注 ,请教使用方法,如何调用?
> 
> > > > > > 把视频地址，传入 xigua("视频地址").start()就可以了，具体的清晰度等需要自己提取，我这里只简单提取了一下
> > > > > 
> > > > > 
> > > > > 貌似不行？ File "C:\Users\Jarvis\Desktop\download\xigua.py", line 28, in **init** '__ac_signature': self.getSign(), ^^^^^^^^^^^^^^ File "C:\Users\Jarvis\Desktop\download\xigua.py", line 42, in getSign ctx = jscode.call("getSign", self.nonce, self.url) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Environment\Python\312\Lib\site-packages\execjs_abstract_runtime_context.py", line 37, in call return self._call(name, *args) ^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Environment\Python\312\Lib\site-packages\execjs_external_runtime.py", line 92, in _call return self._eval("{identifier}.apply(this, {args})".format(identifier=identifier, args=args)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Environment\Python\312\Lib\site-packages\execjs_external_runtime.py", line 78, in _eval return self.exec_(code) ^^^^^^^^^^^^^^^^ File "D:\Environment\Python\312\Lib\site-packages\execjs_abstract_runtime_context.py", line 18, in exec_ return self._exec_(source) ^^^^^^^^^^^^^^^^^^^ File "D:\Environment\Python\312\Lib\site-packages\execjs_external_runtime.py", line 88, in _exec_ return self._extract_result(output) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Environment\Python\312\Lib\site-packages\execjs_external_runtime.py", line 167, in _extract_result raise ProgramError(value) execjs._exceptions.ProgramError: SyntaxError: 缺少标识符、字符串或数字
> > > > 
> > > > 
> > > > 我这边是正常的，你看一下你的nodejs是不是没安装
> > > 
> > > 
> > > 解析后获得的链接，如何进行下载呢，访问后显示是403，有鉴权？
> > 
> > 
> > 请求头带上 Referer:https://www.ixigua.com

你是用什么播放的？可用直接用requests下载

**Comment by TonyD0g** [comment]
> > 大哥，虽然说不会403了，但是视频依旧播放不了，这是我的问题吗，望解答，不胜感激> > > > > > 同步关注 ,请教使用方法,如何调用?
> > 
> > > > > > > 把视频地址，传入 xigua("视频地址").start()就可以了，具体的清晰度等需要自己提取，我这里只简单提取了一下
> > > > > > 
> > > > > > 
> > > > > > 貌似不行？ File "C:\Users\Jarvis\Desktop\download\xigua.py", line 28, in **init** '__ac_signature': self.getSign(), ^^^^^^^^^^^^^^ File "C:\Users\Jarvis\Desktop\download\xigua.py", line 42, in getSign ctx = jscode.call("getSign", self.nonce, self.url) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Environment\Python\312\Lib\site-packages\execjs_abstract_runtime_context.py", line 37, in call return self._call(name, *args) ^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Environment\Python\312\Lib\site-packages\execjs_external_runtime.py", line 92, in _call return self._eval("{identifier}.apply(this, {args})".format(identifier=identifier, args=args)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Environment\Python\312\Lib\site-packages\execjs_external_runtime.py", line 78, in _eval return self.exec_(code) ^^^^^^^^^^^^^^^^ File "D:\Environment\Python\312\Lib\site-packages\execjs_abstract_runtime_context.py", line 18, in exec_ return self._exec_(source) ^^^^^^^^^^^^^^^^^^^ File "D:\Environment\Python\312\Lib\site-packages\execjs_external_runtime.py", line 88, in _exec_ return self._extract_result(output) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Environment\Python\312\Lib\site-packages\execjs_external_runtime.py", line 167, in _extract_result raise ProgramError(value) execjs._exceptions.ProgramError: SyntaxError: 缺少标识符、字符串或数字
> > > > > 
> > > > > 
> > > > > 我这边是正常的，你看一下你的nodejs是不是没安装
> > > > 
> > > > 
> > > > 解析后获得的链接，如何进行下载呢，访问后显示是403，有鉴权？
> > > 
> > > 
> > > 请求头带上 Referer:https://www.ixigua.com
> 
> 你是用什么播放的？可用直接用requests下载

已解决了，感谢。我发现浏览器不行后使用motrix，修改请求头就可以正常下载了。
提一句，那个video_list 解析失败了，需要小小修改一下

**Comment by 9ihbd2DZSMjtsf7vecXjz** [comment]
> > > 大哥，虽然说不会403了，但是视频依旧播放不了，这是我的问题吗，望解答，不胜感激> > > > > > 同步关注 ,请教使用方法,如何调用?
> > > > > > > > 把视频地址，传入 xigua("视频地址").start()就可以了，具体的清晰度等需要自己提取，我这里只简单提取了一下
> > > > > > > 
> > > > > > > 
> > > > > > > 貌似不行？ File "C:\Users\Jarvis\Desktop\download\xigua.py", line 28, in **init** '__ac_signature': self.getSign(), ^^^^^^^^^^^^^^ File "C:\Users\Jarvis\Desktop\download\xigua.py", line 42, in getSign ctx = jscode.call("getSign", self.nonce, self.url) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Environment\Python\312\Lib\site-packages\execjs_abstract_runtime_context.py", line 37, in call return self._call(name, *args) ^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Environment\Python\312\Lib\site-packages\execjs_external_runtime.py", line 92, in _call return self._eval("{identifier}.apply(this, {args})".format(identifier=identifier, args=args)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Environment\Python\312\Lib\site-packages\execjs_external_runtime.py", line 78, in _eval return self.exec_(code) ^^^^^^^^^^^^^^^^ File "D:\Environment\Python\312\Lib\site-packages\execjs_abstract_runtime_context.py", line 18, in exec_ return self._exec_(source) ^^^^^^^^^^^^^^^^^^^ File "D:\Environment\Python\312\Lib\site-packages\execjs_external_runtime.py", line 88, in _exec_ return self._extract_result(output) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Environment\Python\312\Lib\site-packages\execjs_external_runtime.py", line 167, in _extract_result raise ProgramError(value) execjs._exceptions.ProgramError: SyntaxError: 缺少标识符、字符串或数字
> > > > > > 
> > > > > > 
> > > > > > 我这边是正常的，你看一下你的nodejs是不是没安装
> > > > > 
> > > > > 
> > > > > 解析后获得的链接，如何进行下载呢，访问后显示是403，有鉴权？
> > > > 
> > > > 
> > > > 请求头带上 Referer:https://www.ixigua.com
> > 
> > 
> > 你是用什么播放的？可用直接用requests下载
> 
> 已解决了，感谢。我发现浏览器不行后使用motrix，修改请求头就可以正常下载了。 提一句，那个video_list 解析失败了，需要小小修改一下

请问具体怎么使用这个代码进行西瓜的解析呢? 比如 

python xigua.py https://www.ixigua.com/7417382021112005157?logTag=5288841dfe121d34e5f3
  File "C:\Users\admin\Desktop\123\Dlink_Parse-master\xigua.py", line 64
    iv = bytes.fromhex(hashlib.md5(f"{key.decode("utf8")}_{vid}".encode("utf8")).hexdigest())
                                                  ^^^^
SyntaxError: f-string: unmatched '('

**Comment by jym66** [comment]
> > > > 大哥，虽然说不会403了，但是视频依旧播放不了，这是我的问题吗，望解答，不胜感激> > > > > > 同步关注 ,请教使用方法,如何调用?
> > > > > > > > > 把视频地址，传入 xigua("视频地址").start()就可以了，具体的清晰度等需要自己提取，我这里只简单提取了一下
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 貌似不行？ File "C:\Users\Jarvis\Desktop\download\xigua.py", line 28, in **init** '__ac_signature': self.getSign(), ^^^^^^^^^^^^^^ File "C:\Users\Jarvis\Desktop\download\xigua.py", line 42, in getSign ctx = jscode.call("getSign", self.nonce, self.url) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Environment\Python\312\Lib\site-packages\execjs_abstract_runtime_context.py", line 37, in call return self._call(name, *args) ^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Environment\Python\312\Lib\site-packages\execjs_external_runtime.py", line 92, in _call return self._eval("{identifier}.apply(this, {args})".format(identifier=identifier, args=args)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Environment\Python\312\Lib\site-packages\execjs_external_runtime.py", line 78, in _eval return self.exec_(code) ^^^^^^^^^^^^^^^^ File "D:\Environment\Python\312\Lib\site-packages\execjs_abstract_runtime_context.py", line 18, in exec_ return self._exec_(source) ^^^^^^^^^^^^^^^^^^^ File "D:\Environment\Python\312\Lib\site-packages\execjs_external_runtime.py", line 88, in _exec_ return self._extract_result(output) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Environment\Python\312\Lib\site-packages\execjs_external_runtime.py", line 167, in _extract_result raise ProgramError(value) execjs._exceptions.ProgramError: SyntaxError: 缺少标识符、字符串或数字
> > > > > > > 
> > > > > > > 
> > > > > > > 我这边是正常的，你看一下你的nodejs是不是没安装
> > > > > > 
> > > > > > 
> > > > > > 解析后获得的链接，如何进行下载呢，访问后显示是403，有鉴权？
> > > > > 
> > > > > 
> > > > > 请求头带上 Referer:https://www.ixigua.com
> > > 
> > > 
> > > 你是用什么播放的？可用直接用requests下载
> > 
> > 
> > 已解决了，感谢。我发现浏览器不行后使用motrix，修改请求头就可以正常下载了。 提一句，那个video_list 解析失败了，需要小小修改一下
> 
> 请问具体怎么使用这个代码进行西瓜的解析呢? 比如
> 
> python xigua.py https://www.ixigua.com/7417382021112005157?logTag=5288841dfe121d34e5f3 File "C:\Users\admin\Desktop\123\Dlink_Parse-master\xigua.py", line 64 iv = bytes.fromhex(hashlib.md5(f"{key.decode("utf8")}_{vid}".encode("utf8")).hexdigest()) ^^^^ SyntaxError: f-string: unmatched '('

  xigua("视频地址写在这里").start() 之后运行
