### ISSUE TITLE
爱奇艺的是不是失效了

### ISSUE THREAD

**Issue by TonyD0g** [jym66/Dlink_Parse#12]
返回的数据显示签名不正确

**Comment by jym66** [comment]
是的，毕竟这个项目是很久之前写的

**Comment by TonyD0g** [comment]
> 是的，毕竟这个项目是很久之前写的

大佬不考虑更新了吗

**Comment by jym66** [comment]
> > 是的，毕竟这个项目是很久之前写的
> 
> 大佬不考虑更新了吗

有时间看一下

**Comment by jym66** [comment]
c96d7fb1a9590bf712bde513b9d160c8f9fe8a41

**Comment by TonyD0g** [comment]
> [c96d7fb](https://github.com/jym66/Dlink_Parse/commit/c96d7fb1a9590bf712bde513b9d160c8f9fe8a41)

vip视频的是不是无法解析：
视频链接：
   https://www.iqiyi.com/v_19rrk2h45c.html?vfrmrst=0&vfrm=3&vfrmblk=pca_115_number_enlarge
报错：
Traceback (most recent call last):
  File "iqiyi.py", line 92, in <module>
    iqiyi(
  File "iqiyi.py", line 86, in start
    params = self.join_params()
  File "iqiyi.py", line 34, in join_params
    tvid, vid = self.get_tvid()
  File "iqiyi.py", line 31, in get_tvid
    return tvid.group(1), vid.group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by jym66** [comment]
> > [c96d7fb](https://github.com/jym66/Dlink_Parse/commit/c96d7fb1a9590bf712bde513b9d160c8f9fe8a41)
> 
> vip视频的是不是无法解析： 视频链接： https://www.iqiyi.com/v_19rrk2h45c.html?vfrmrst=0&vfrm=3&vfrmblk=pca_115_number_enlarge 报错： Traceback (most recent call last): File "iqiyi.py", line 92, in iqiyi( File "iqiyi.py", line 86, in start params = self.join_params() File "iqiyi.py", line 34, in join_params tvid, vid = self.get_tvid() File "iqiyi.py", line 31, in get_tvid return tvid.group(1), vid.group(1) AttributeError: 'NoneType' object has no attribute 'group'

看了一下这个是直接跳vip购买页面了，带一下cookie看看，我这边没有会员

**Comment by TonyD0g** [comment]
> > > [c96d7fb](https://github.com/jym66/Dlink_Parse/commit/c96d7fb1a9590bf712bde513b9d160c8f9fe8a41)
> > 
> > vip视频的是不是无法解析： 视频链接： https://www.iqiyi.com/v_19rrk2h45c.html?vfrmrst=0&vfrm=3&vfrmblk=pca_115_number_enlarge 报错： Traceback (most recent call last): File "iqiyi.py", line 92, in iqiyi( File "iqiyi.py", line 86, in start params = self.join_params() File "iqiyi.py", line 34, in join_params tvid, vid = self.get_tvid() File "iqiyi.py", line 31, in get_tvid return tvid.group(1), vid.group(1) AttributeError: 'NoneType' object has no attribute 'group'
> 
> 看了一下这个是直接跳vip购买页面了，带一下cookie看看，我这边没有会员

我也没有会员……
但iqiyi.py里的网址是可以正常解析的（我切换到vip才能看的集也可以解析），有点奇怪

**Comment by jym66** [comment]
> > > > [c96d7fb](https://github.com/jym66/Dlink_Parse/commit/c96d7fb1a9590bf712bde513b9d160c8f9fe8a41)
> > > 
> > > 
> > > vip视频的是不是无法解析： 视频链接： https://www.iqiyi.com/v_19rrk2h45c.html?vfrmrst=0&vfrm=3&vfrmblk=pca_115_number_enlarge 报错： Traceback (most recent call last): File "iqiyi.py", line 92, in iqiyi( File "iqiyi.py", line 86, in start params = self.join_params() File "iqiyi.py", line 34, in join_params tvid, vid = self.get_tvid() File "iqiyi.py", line 31, in get_tvid return tvid.group(1), vid.group(1) AttributeError: 'NoneType' object has no attribute 'group'
> > 
> > 
> > 看了一下这个是直接跳vip购买页面了，带一下cookie看看，我这边没有会员
> 
> 我也没有会员…… 但iqiyi.py里的网址是可以正常解析的（我切换到vip才能看的集也可以解析），有点奇怪

他直接跳转vip购买页面，导致获取不到视频vid，iqiyi.py里的那个视频是可以直接播放的。

**Comment by TonyD0g** [comment]
> > > > > [c96d7fb](https://github.com/jym66/Dlink_Parse/commit/c96d7fb1a9590bf712bde513b9d160c8f9fe8a41)
> > > > 
> > > > 
> > > > vip视频的是不是无法解析： 视频链接： https://www.iqiyi.com/v_19rrk2h45c.html?vfrmrst=0&vfrm=3&vfrmblk=pca_115_number_enlarge 报错： Traceback (most recent call last): File "iqiyi.py", line 92, in iqiyi( File "iqiyi.py", line 86, in start params = self.join_params() File "iqiyi.py", line 34, in join_params tvid, vid = self.get_tvid() File "iqiyi.py", line 31, in get_tvid return tvid.group(1), vid.group(1) AttributeError: 'NoneType' object has no attribute 'group'
> > > 
> > > 
> > > 看了一下这个是直接跳vip购买页面了，带一下cookie看看，我这边没有会员
> > 
> > 我也没有会员…… 但iqiyi.py里的网址是可以正常解析的（我切换到vip才能看的集也可以解析），有点奇怪
> 
> 他直接跳转vip购买页面，导致获取不到视频vid，iqiyi.py里的那个视频是可以直接播放的。


解决办法看来只有充会员？

**Comment by jym66** [comment]
> > > > > > [c96d7fb](https://github.com/jym66/Dlink_Parse/commit/c96d7fb1a9590bf712bde513b9d160c8f9fe8a41)
> > > > > 
> > > > > 
> > > > > vip视频的是不是无法解析： 视频链接： https://www.iqiyi.com/v_19rrk2h45c.html?vfrmrst=0&vfrm=3&vfrmblk=pca_115_number_enlarge 报错： Traceback (most recent call last): File "iqiyi.py", line 92, in iqiyi( File "iqiyi.py", line 86, in start params = self.join_params() File "iqiyi.py", line 34, in join_params tvid, vid = self.get_tvid() File "iqiyi.py", line 31, in get_tvid return tvid.group(1), vid.group(1) AttributeError: 'NoneType' object has no attribute 'group'
> > > > 
> > > > 
> > > > 看了一下这个是直接跳vip购买页面了，带一下cookie看看，我这边没有会员
> > > 
> > > 
> > > 我也没有会员…… 但iqiyi.py里的网址是可以正常解析的（我切换到vip才能看的集也可以解析），有点奇怪
> > 
> > 
> > 他直接跳转vip购买页面，导致获取不到视频vid，iqiyi.py里的那个视频是可以直接播放的。
> 
> 解决办法看来只有充会员？

是的，如果本身没有会员的话是获取不到会员视频的
