### ISSUE TITLE
抖音视频链接请求无内容

### ISSUE THREAD

**Issue by palysh** [jym66/Dlink_Parse#13]
你好，我也想做一个小东西希望解析抖音的视频然后下载
这个接口
https://www.iesdouyin.com/web/api/v2/aweme/iteminfo/?item_ids=7425538313139866916

7425538313139866916这个id是我获取的视频id,但请求这个接口返回200  ，没有内容

你知道咋回事吗

**Comment by jym66** [comment]
接口更新了，需要重新分析
