### ISSUE TITLE
西瓜视频的main_url好像都是错误的，不是‘aHR0’开头的

### ISSUE THREAD

**Issue by BinZhu-ece** [jym66/Dlink_Parse#9]
![image](https://github.com/jym66/Dlink_Parse/assets/75013190/db867c8a-df21-4655-be68-9a87dd692497)

**Comment by jym66** [comment]
时间太久了，他们api应该更新了

**Comment by BinZhu-ece** [comment]
> 时间太久了，他们api应该更新了

嗷嗷，好的，感谢大佬！请问后续还会更新吗？

**Comment by jym66** [comment]
> > 时间太久了，他们api应该更新了
> 
> 嗷嗷，好的，感谢大佬！请问后续还会更新吗？

已更新 703ce082aa843fe86e12a95fcf1e329f80fbd5d3

**Comment by TonyD0g** [comment]
> ![image](https://private-user-images.githubusercontent.com/75013190/346335472-db867c8a-df21-4655-be68-9a87dd692497.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxMDk3NzAsIm5iZiI6MTcyODEwOTQ3MCwicGF0aCI6Ii83NTAxMzE5MC8zNDYzMzU0NzItZGI4NjdjOGEtZGYyMS00NjU1LWJlNjgtOWE4N2RkNjkyNDk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA1VDA2MjQzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlYmFjMjg4M2RmNjA0NmI2Y2I2ZTRkYWMwNzMwNTk5Y2I4ZjFlZDgzZWVlNmJlNGJjOWIzNjc3MmNkNWQ2MDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.oDfXQWfAj00dtTju-cwFR_Eb1aDpgzI6srCC3QXNigE)

您好，获取到main_url后如何进行下载呢？ 浏览器访问是403
